### ISSUE TITLE
Can't connect to Last.fm

### ISSUE THREAD

**Issue by sambeckwith** [newgiin/cloudplayer-scrobbler#11]
Clicking the "Yes, allow access" button on the Last.fm website redirects me to the Last.fm homepage and nothing else happens.

**Comment by newgiin** [comment]
This is expected behavior (returning you to the last.fm homepage). At this point, you should be logged in and you when you go to Play or refresh your current Play page, it should start scrobbling music. When you click on the extension icon again does it say "Logged in as {your_user_name}" in the bottom right?

**Comment by sambeckwith** [comment]
No, that's the problem: It still says "Connect to Last.fm" in the bottom
right corner of the extension icon. And yes, I'm signed into Last.fm :-)

On 23 July 2014 19:45, Andrew Nguyen notifications@github.com wrote:

> This is expected behavior (returning you to the last.fm homepage). At
> this point, you should be logged in and you when you go to Play or refresh
> your current Play page, it should start scrobbling music. When you click on
> the extension icon again does it say "Logged in as {your_user_name}" in the
> bottom right?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/newgiin/cloudplayer-scrobbler/issues/11#issuecomment-49909192
> .

## 

Sam Beckwith
Writer/Editor
Prague, Czech Republic
Mobile: (+420) 603 981 976

**Comment by sambeckwith** [comment]
Google Play Last.fm Scrobbler now seems to be working for me at home but
not at the office so maybe it's a firewall issue.

On 24 July 2014 09:26, Sam Beckwith sambeckwith@gmail.com wrote:

> No, that's the problem: It still says "Connect to Last.fm" in the bottom
> right corner of the extension icon. And yes, I'm signed into Last.fm :-)
> 
> On 23 July 2014 19:45, Andrew Nguyen notifications@github.com wrote:
> 
> > This is expected behavior (returning you to the last.fm homepage). At
> > this point, you should be logged in and you when you go to Play or refresh
> > your current Play page, it should start scrobbling music. When you click on
> > the extension icon again does it say "Logged in as {your_user_name}" in the
> > bottom right?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/newgiin/cloudplayer-scrobbler/issues/11#issuecomment-49909192
> > .
> 
> ## 
> 
> Sam Beckwith
> Writer/Editor
> Prague, Czech Republic
> Mobile: (+420) 603 981 976

## 

Sam Beckwith
Writer/Editor
Prague, Czech Republic
Mobile: (+420) 603 981 976

**Comment by newgiin** [comment]
Great, also occasionally the Last.fm services the extension uses simply aren't working, might have been that.
