### ISSUE TITLE
Keyboard media buttons support

### ISSUE THREAD

**Issue by andrey-shikhov** [newgiin/cloudplayer-scrobbler#12]
Please add media keyssupport, I think this is not so hard, 
see https://developer.chrome.com/extensions/commands

**Comment by newgiin** [comment]
Good idea, will work on it this weekend. I'll probably bind them to the media keys by default.

**Comment by newgiin** [comment]
498219d8f1280fdaf379d097a9ad4802b001ecf8

From the updated extension description:
"""
Keyboard shortcuts:
Keyboard shortcuts can be edited at chrome://extensions or by going to "Chrome menu"(upper right icon in browser) > Tools > Extensions > "Keyboard shortcuts"(at bottom right of page).

Defaults_:
Toggle_play, next/previous_song\_*: Keyboard media keys
Open Play tab: Ctrl+Shift+4

_Current users will not have their keyboard shortcuts updated and you will have to update your shortcuts manually as described above.
*_Currently issues with Linux media key support, so default shortcut for Linux is Ctrl+Shift+{1,2,3} for previous_song, toggle_play, next_song, respectively.
"""

Please let me know if you have any issues.
