### ISSUE TITLE
Not sending "albumArtist" on nowPlaying

### ISSUE THREAD

**Issue by mbdroid** [newgiin/cloudplayer-scrobbler#17]
When scrobbling a track the field "albumArtist" is not sent. This becomes problematic when listening to a compilation album, or a soundtrack because Last.fm tracks each Artist-Album pair as a different album in charts.

**Comment by newgiin** [comment]
Fixed, updated version should be live soon.

2187bac7a01b21fb1a00efa3396083f2b82f5a90

**Comment by mbdroid** [comment]
Thank you for the update!
