### ISSUE TITLE
white spaces on 'albumArtist' revisted

### ISSUE THREAD

**Issue by angmyu** [newgiin/cloudplayer-scrobbler#19]
Thanks for fast fix, but it still has bug.
Please check following 'Blasterjaxx &+DBSTF' and 'Armin van+Buuren':

Wrong: http://www.last.fm/music/Blasterjaxx+&%252BDBSTF/Beautiful+World
Correct: http://www.last.fm/music/Blasterjaxx+&+DBSTF/Beautiful+World

Wrong: http://www.last.fm/music/Armin+van%252BBuuren/Together+%28In+A+State+Of+Trance%29
Correct: http://www.last.fm/music/Armin+van+Buuren/Together+%28In+A+State+Of+Trance%29

Still, many other scrobblers don't support scrobbling 'album artist' because it is officially an option of track submission method in API. So it may be confused for making  statistics by using with other scrobblers in different environment (e.g. Mobile or PC;foobar2000, etc.) Well, it may be kinda trivial thing but I think someone may cares.

Anyway, big thanks for your volunteer! I really appreciate it!

**Comment by newgiin** [comment]
reopened the other bug https://github.com/newgiin/cloudplayer-scrobbler/issues/18, closing this one as duplicate. Thanks for reporting this, I thought I already tested for these special characters and should be sending them correctly, might be something funny on the last.fm side, I'll look into this soon.
