### ISSUE TITLE
Apply material design to popup

### ISSUE THREAD

**Issue by nathanbrock** [newgiin/cloudplayer-scrobbler#25]
Hey,

Firstly, huge thanks for the great extension!

I appreciate pull request #24 is currently lined up, but I thought it would be great to see the popup with Googles material design. I've included a quick screencast / screenshot below, if anyone would take a look and add any feedback (choice of colour, layout ect) that would be awesome. @newgiin, if you're happy with it, I'll tie up the loose ends and submit a pull request.

You can see the update in action at http://quick.as/4Yw2UBjqw

![screen shot 2015-04-23 at 22 26 46](https://cloud.githubusercontent.com/assets/851698/7307973/4e083ef6-ea08-11e4-81de-28e3b909fba7.png)

Cheers!

**Comment by newgiin** [comment]
Hey thanks for making this re-design, but I honestly just like the current design more. I prefer keeping the popup small and not having to click through any menus.
