### ISSUE TITLE
Extension removed from Chrome web store

### ISSUE THREAD

**Issue by wesQ3** [newgiin/cloudplayer-scrobbler#47]
Today I noticed the extension was disabled in my browser and has a warning in my extensions list.

> This extension violates the Chrome Web Store policy.

Since the page has been removed from the store it was even difficult to find this repo again. The store link returns 404 now.

Why was it removed from the Store? I've never had any problems with this extension.

**Comment by newgiin** [comment]
I recently applied to have it put back up after removing the tabs permission (https://github.com/newgiin/cloudplayer-scrobbler/commit/35f1571000741865c9de19a8a88d28d7a52eb279). They deemed that it didn't need it, even though it's used for the hotkey to switch to the Music tab, so I guess we'll just have to do without that feature now. Still waiting to see if it's approved.

**Comment by newgiin** [comment]
It's back up now.
