### ISSUE TITLE
Google Play LastFM Scrobbler - NOT User "0"?

### ISSUE THREAD

**Issue by ammalena** [newgiin/cloudplayer-scrobbler#6]
Scrobbler seems to work well when the only person logged in is the user who the Google Play account is being scrobbled from.

However, at work, I login primarily (/u/0 or ?u=0 on the URL) as my work Google account, THEN into my person account (/u/1 or ?u=1) secondarily.  The scrobbler does not recognize this.

Any workaround available, or update coming for this?

Thanks!

**Comment by newgiin** [comment]
Hey, thanks for the report, I'll look into it tonight.

**Comment by ammalena** [comment]
No prob.  Probably not a common occurrence, but then again, I imagine more and more people will run into this as long as Google Business Accounts proliferate as much as Google hopes.  (hah)  Logging as as my PERSONAL first causes several other issues, else I'd just do that.

**Comment by newgiin** [comment]
Hmm, I tried scrobbling on a secondary account and it seems to be working on my end. My Play URL looks like "https://play.google.com/music/listen?u=1#/album//{ARTIST_NAME}/{ALBUM_NAME}". 

I performed these steps:
1. Opened Chrome
2. Went to music.google.com
3. Clicked on the upper-right to change my profile to the second account
4. Played a song.

Going directly there also works for me as well. Any other special steps you're taking? 

It should scrobble properly as long as the URL matches "*://play.google.com/music/listen*" where '*' is any number of additional characters. 

Try disconnecting your last.fm account from the extension and reconnecting via "Connect to Last.fm" in the extension. Also, make sure to refresh your Google Play page after reconnecting. It shouldn't depend on which Google account is being used.

**Comment by ammalena** [comment]
Okay, I'm very confused.  I don't normally open tickets like this on anything without investigating thoroughly.  (sigh)

I DID just reinstall your script for the first time in 2+ months today, and I did ALREADY have Play running at the time.

I literally just refreshed Play, and started a song... and it showed up instantly in the Scrobbler menu as playing... went to my Last.FM page... there's the song.

http://www.last.fm/user/AMMalena

I'm really sorry.  It REALLY DID have this issue, but I'd moved to a new computer and just today reinstalled the Scrobbler, and ASSumed it was having the same issue.

Or, I'm not in Universe-626 and you are better than your other-Earth counterpart.  (rofl)   Glad to have my scrobbling back on at Work now along with my phone and home computer.  ;)

Thanks.  Sorry.  <bow>

**Comment by newgiin** [comment]
No problem!
