### ISSUE TITLE
Music playback occasionally stops at specific times

### ISSUE THREAD

**Issue by michael73072** [newgiin/cloudplayer-scrobbler#7]
I noticed a problem a couple weeks ago where Google Play would occasionally stop playback at 7, 15, 30, 45, or 90 seconds into a song. It would then take several minutes for playback to resume; you couldn't force it to start. Clearing the cache and cookies did nothing. I thought for awhile that it was a problem with Google Play Music, but then today I remembered that I have this extension installed. I disabled it, and what do you know! No more random pausing! I then re-enabled the extension and the problem hasn't started again, so I don't really know what's going on. Maybe it's a one time thing?

Chrome Version: 34.0.1847.131
Windows 7 64-bit

**Comment by newgiin** [comment]
Hopefully it's a one time thing, can't think of anything off the top of my head in the extension's code that would make it pause at doubling intervals. If it persists, then I will look into it. Thanks for the feedback.
